### ISSUE TITLE
Scanning is not compatible with many phones

### ISSUE THREAD

**Issue by benjamin-klamerek** [benjamin-klamerek/fantasy-realm-scoring#12]
Scan can generate a crash on some phones : 

FATAL EXCEPTION: main
Process: com.klamerek.fantasyrealms, PID: 29872
java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
	at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:762)
	at com.google.mlkit.vision.common.internal.ImageConvertUtils.zza(com.google.mlkit:vision-common@@16.5.0:1)
	at com.google.mlkit.vision.common.internal.ImageConvertUtils.convertJpegToUpRightBitmap(com.google.mlkit:vision-common@@16.5.0:10)
	at com.google.mlkit.vision.common.InputImage.fromMediaImage(com.google.mlkit:vision-common@@16.5.0:10)
	at com.klamerek.fantasyrealms.screen.ScanActivity$MyImageCapturedCallback.onCaptureSuccess(ScanActivity.kt:91)
	at androidx.camera.core.ImageCapture$ImageCaptureRequest.lambda$dispatchImage$0$ImageCapture$ImageCaptureRequest(ImageCapture.java:2395)
	at androidx.camera.core.ImageCapture$ImageCaptureRequest$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Seems linked to image format. 

One example : Redmi 6A Android 8.1 (SDK 27) OpenGL ES ARM_V7

**Comment by benjamin-klamerek** [comment]
For next version : at least add better error message than crashing the app

**Comment by benjamin-klamerek** [comment]
v0.16 should improve it
